name: CI/CD for Main Branch pushes

on:
    push:
        branches:
            - main

jobs:
    buid-and-deploy:
     name: Build, Test and Deploy Spring Boot App
     runs-on: ubuntu-latest
     steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: Setup JDK 17
          uses: actions/setup-java@v4
          with:
            distribution: "sapmachine"
            java-version: 17
        - name: Build the application
          run: |
            mvn clean
            mvn -B package --file pom.xml

        - name: Run Unit Tests
          run: mvn -B test --file pom.xml
       
        - name: Set Up Docker BuildX
          uses: docker/setup-buildx-action@v3

        - name: Login Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Build and Push Docker
          uses: docker/build-push-action@v6
          with:
            context: . 
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot-for-bigginers:${{ github.sha }}

        
